server:
  port: 8082

app:
  cypher:
    key:
      size: 1024
    algorithm: RSA

management:
  server:
    port: 8082
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health","prometheus", "metrics" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true